#if !defined(INCLUDED_WHALECONF_H)
#define INCLUDED_WHALECONF_H

#ifndef IS_COLORING_MAX
#define IS_COLORING_MAX 65535
#endif

#ifndef STDC_HEADERS
#define STDC_HEADERS 1
#endif

#ifndef MPIU_COLORING_VALUE
#define MPIU_COLORING_VALUE MPI_UNSIGNED_SHORT
#endif

#ifndef WHALE_UINTPTR_T
#define WHALE_UINTPTR_T uintptr_t
#endif

#ifndef WHALE_HAVE_PTHREAD
#define WHALE_HAVE_PTHREAD 1
#endif

#ifndef WHALE_DEPRECATED
#define WHALE_DEPRECATED(why) __attribute((deprecated(why)))
#endif

#ifndef WHALE_STATIC_INLINE
#define WHALE_STATIC_INLINE static inline
#endif

#ifndef WHALE_REPLACE_DIR_SEPARATOR
#define WHALE_REPLACE_DIR_SEPARATOR '\\'
#endif

#ifndef WHALE_RESTRICT
#define WHALE_RESTRICT  __restrict__
#endif

#ifndef WHALE_HAVE_SO_REUSEADDR
#define WHALE_HAVE_SO_REUSEADDR 1
#endif

#ifndef WHALE_HAVE_MPI
#define WHALE_HAVE_MPI 1
#endif

#ifndef WHALE_PREFETCH_HINT_T2
#define WHALE_PREFETCH_HINT_T2 _MM_HINT_T2
#endif

#ifndef WHALE_PREFETCH_HINT_T0
#define WHALE_PREFETCH_HINT_T0 _MM_HINT_T0
#endif

#ifndef WHALE_PREFETCH_HINT_T1
#define WHALE_PREFETCH_HINT_T1 _MM_HINT_T1
#endif

#ifndef WHALE__GNU_SOURCE
#define WHALE__GNU_SOURCE 1
#endif

#ifndef WHALE_HAVE_FORTRAN
#define WHALE_HAVE_FORTRAN 1
#endif

#ifndef WHALE_HAVE_X
#define WHALE_HAVE_X 1
#endif

#ifndef WHALE_HAVE_HYPRE
#define WHALE_HAVE_HYPRE 1
#endif

#ifndef WHALE_LIB_DIR
#define WHALE_LIB_DIR "/opt/Work/FEniCS/lib"
#endif

#ifndef WHALE_HAVE_PARMETIS
#define WHALE_HAVE_PARMETIS 1
#endif

#ifndef WHALE_USE_SOCKET_VIEWER
#define WHALE_USE_SOCKET_VIEWER 1
#endif

#ifndef WHALE_SLSUFFIX
#define WHALE_SLSUFFIX "so"
#endif

#ifndef WHALE_FUNCTION_NAME_CXX
#define WHALE_FUNCTION_NAME_CXX __func__
#endif

#ifndef WHALE_HAVE_UMFPACK
#define WHALE_HAVE_UMFPACK 1
#endif

#ifndef WHALE_HAVE_MUMPS
#define WHALE_HAVE_MUMPS 1
#endif

#ifndef WHALE_HAVE_ATOLL
#define WHALE_HAVE_ATOLL 1
#endif

#ifndef WHALE_HAVE_DOUBLE_ALIGN_MALLOC
#define WHALE_HAVE_DOUBLE_ALIGN_MALLOC 1
#endif

#ifndef WHALE_UNUSED
#define WHALE_UNUSED __attribute((unused))
#endif

#ifndef WHALE_FUNCTION_NAME_C
#define WHALE_FUNCTION_NAME_C __func__
#endif

#ifndef WHALE_HAVE_VALGRIND
#define WHALE_HAVE_VALGRIND 1
#endif

#ifndef WHALE_USE_SINGLE_LIBRARY
#define WHALE_USE_SINGLE_LIBRARY 1
#endif

#ifndef WHALE_HAVE_BUILTIN_EXPECT
#define WHALE_HAVE_BUILTIN_EXPECT 1
#endif

#ifndef WHALE_HAVE_PTSCOTCH
#define WHALE_HAVE_PTSCOTCH 1
#endif

#ifndef WHALE_HAVE_METIS
#define WHALE_HAVE_METIS 1
#endif

#ifndef WHALE_DIR_SEPARATOR
#define WHALE_DIR_SEPARATOR '/'
#endif

#ifndef WHALE_PATH_SEPARATOR
#define WHALE_PATH_SEPARATOR ':'
#endif

#ifndef WHALE__BSD_SOURCE
#define WHALE__BSD_SOURCE 1
#endif

#ifndef WHALE_HAVE_XMMINTRIN_H
#define WHALE_HAVE_XMMINTRIN_H 1
#endif

#ifndef WHALE_PREFETCH_HINT_NTA
#define WHALE_PREFETCH_HINT_NTA _MM_HINT_NTA
#endif

#ifndef WHALE_Prefetch
#define WHALE_Prefetch(a,b,c) _mm_prefetch((const char*)(a),(c))
#endif

#ifndef WHALE_HAVE_BLASLAPACK
#define WHALE_HAVE_BLASLAPACK 1
#endif

#ifndef WHALE_HAVE_FLOAT_H
#define WHALE_HAVE_FLOAT_H 1
#endif

#ifndef WHALE_HAVE_STRING_H
#define WHALE_HAVE_STRING_H 1
#endif

#ifndef WHALE_HAVE_SYS_TIMES_H
#define WHALE_HAVE_SYS_TIMES_H 1
#endif

#ifndef WHALE_HAVE_SYS_TYPES_H
#define WHALE_HAVE_SYS_TYPES_H 1
#endif

#ifndef WHALE_HAVE_ENDIAN_H
#define WHALE_HAVE_ENDIAN_H 1
#endif

#ifndef WHALE_HAVE_SYS_PROCFS_H
#define WHALE_HAVE_SYS_PROCFS_H 1
#endif

#ifndef WHALE_HAVE_DLFCN_H
#define WHALE_HAVE_DLFCN_H 1
#endif

#ifndef WHALE_HAVE_SCHED_H
#define WHALE_HAVE_SCHED_H 1
#endif

#ifndef WHALE_HAVE_STDINT_H
#define WHALE_HAVE_STDINT_H 1
#endif

#ifndef WHALE_HAVE_LINUX_KERNEL_H
#define WHALE_HAVE_LINUX_KERNEL_H 1
#endif

#ifndef WHALE_HAVE_TIME_H
#define WHALE_HAVE_TIME_H 1
#endif

#ifndef WHALE_HAVE_MATH_H
#define WHALE_HAVE_MATH_H 1
#endif

#ifndef WHALE_HAVE_STDLIB_H
#define WHALE_HAVE_STDLIB_H 1
#endif

#ifndef WHALE_HAVE_SYS_PARAM_H
#define WHALE_HAVE_SYS_PARAM_H 1
#endif

#ifndef WHALE_HAVE_PTHREAD_H
#define WHALE_HAVE_PTHREAD_H 1
#endif

#ifndef WHALE_HAVE_UNISTD_H
#define WHALE_HAVE_UNISTD_H 1
#endif

#ifndef WHALE_HAVE_SYS_WAIT_H
#define WHALE_HAVE_SYS_WAIT_H 1
#endif

#ifndef WHALE_HAVE_SETJMP_H
#define WHALE_HAVE_SETJMP_H 1
#endif

#ifndef WHALE_HAVE_LIMITS_H
#define WHALE_HAVE_LIMITS_H 1
#endif

#ifndef WHALE_HAVE_SYS_UTSNAME_H
#define WHALE_HAVE_SYS_UTSNAME_H 1
#endif

#ifndef WHALE_HAVE_NETINET_IN_H
#define WHALE_HAVE_NETINET_IN_H 1
#endif

#ifndef WHALE_HAVE_FENV_H
#define WHALE_HAVE_FENV_H 1
#endif

#ifndef WHALE_HAVE_SYS_SOCKET_H
#define WHALE_HAVE_SYS_SOCKET_H 1
#endif

#ifndef WHALE_HAVE_MEMORY_H
#define WHALE_HAVE_MEMORY_H 1
#endif

#ifndef WHALE_HAVE_SEARCH_H
#define WHALE_HAVE_SEARCH_H 1
#endif

#ifndef WHALE_HAVE_SYS_RESOURCE_H
#define WHALE_HAVE_SYS_RESOURCE_H 1
#endif

#ifndef WHALE_TIME_WITH_SYS_TIME
#define WHALE_TIME_WITH_SYS_TIME 1
#endif

#ifndef WHALE_HAVE_NETDB_H
#define WHALE_HAVE_NETDB_H 1
#endif

#ifndef WHALE_HAVE_MALLOC_H
#define WHALE_HAVE_MALLOC_H 1
#endif

#ifndef WHALE_HAVE_PWD_H
#define WHALE_HAVE_PWD_H 1
#endif

#ifndef WHALE_HAVE_FCNTL_H
#define WHALE_HAVE_FCNTL_H 1
#endif

#ifndef WHALE_HAVE_STRINGS_H
#define WHALE_HAVE_STRINGS_H 1
#endif

#ifndef WHALE_HAVE_SYS_SYSINFO_H
#define WHALE_HAVE_SYS_SYSINFO_H 1
#endif

#ifndef WHALE_HAVE_SYS_TIME_H
#define WHALE_HAVE_SYS_TIME_H 1
#endif

#ifndef WHALE_USING_F90
#define WHALE_USING_F90 1
#endif

#ifndef WHALE_USING_F2003
#define WHALE_USING_F2003 1
#endif

#ifndef WHALE_HAVE_RTLD_NOW
#define WHALE_HAVE_RTLD_NOW 1
#endif

#ifndef WHALE_HAVE_RTLD_LOCAL
#define WHALE_HAVE_RTLD_LOCAL 1
#endif

#ifndef WHALE_HAVE_RTLD_LAZY
#define WHALE_HAVE_RTLD_LAZY 1
#endif

#ifndef WHALE_C_STATIC_INLINE
#define WHALE_C_STATIC_INLINE static inline
#endif

#ifndef WHALE_HAVE_FORTRAN_UNDERSCORE
#define WHALE_HAVE_FORTRAN_UNDERSCORE 1
#endif

#ifndef WHALE_HAVE_CXX_NAMESPACE
#define WHALE_HAVE_CXX_NAMESPACE 1
#endif

#ifndef WHALE_HAVE_RTLD_GLOBAL
#define WHALE_HAVE_RTLD_GLOBAL 1
#endif

#ifndef WHALE_C_RESTRICT
#define WHALE_C_RESTRICT  __restrict__
#endif

#ifndef WHALE_CXX_RESTRICT
#define WHALE_CXX_RESTRICT  __restrict__
#endif

#ifndef WHALE_CXX_STATIC_INLINE
#define WHALE_CXX_STATIC_INLINE static inline
#endif

#ifndef WHALE_HAVE_LIBBLAS
#define WHALE_HAVE_LIBBLAS 1
#endif

#ifndef WHALE_HAVE_LIBZ
#define WHALE_HAVE_LIBZ 1
#endif

#ifndef WHALE_HAVE_LIBDL
#define WHALE_HAVE_LIBDL 1
#endif

#ifndef WHALE_HAVE_LIBGFORTRAN
#define WHALE_HAVE_LIBGFORTRAN 1
#endif

#ifndef WHALE_HAVE_LIBSCALAPACK
#define WHALE_HAVE_LIBSCALAPACK 1
#endif

#ifndef WHALE_HAVE_LIBMETIS
#define WHALE_HAVE_LIBMETIS 1
#endif

#ifndef WHALE_HAVE_LIBLAPACK
#define WHALE_HAVE_LIBLAPACK 1
#endif

#ifndef WHALE_HAVE_LIBPTSCOTCH
#define WHALE_HAVE_LIBPTSCOTCH 1
#endif

#ifndef WHALE_HAVE_LIBM
#define WHALE_HAVE_LIBM 1
#endif

#ifndef WHALE_HAVE_LIBSCOTCHERR
#define WHALE_HAVE_LIBSCOTCHERR 1
#endif

#ifndef WHALE_HAVE_LIBDMUMPS
#define WHALE_HAVE_LIBDMUMPS 1
#endif

#ifndef WHALE_HAVE_LIBPTESMUMPS
#define WHALE_HAVE_LIBPTESMUMPS 1
#endif

#ifndef WHALE_HAVE_LIBMUMPS_COMMON
#define WHALE_HAVE_LIBMUMPS_COMMON 1
#endif

#ifndef WHALE_HAVE_LIBPTHREAD
#define WHALE_HAVE_LIBPTHREAD 1
#endif

#ifndef WHALE_HAVE_LIBMPI_F77
#define WHALE_HAVE_LIBMPI_F77 1
#endif

#ifndef WHALE_HAVE_LIBPARMETIS
#define WHALE_HAVE_LIBPARMETIS 1
#endif

#ifndef WHALE_HAVE_LIBZMUMPS
#define WHALE_HAVE_LIBZMUMPS 1
#endif

#ifndef WHALE_HAVE_LIBMPI_F90
#define WHALE_HAVE_LIBMPI_F90 1
#endif

#ifndef WHALE_HAVE_LIBHYPRE
#define WHALE_HAVE_LIBHYPRE 1
#endif

#ifndef WHALE_HAVE_LIBAMD
#define WHALE_HAVE_LIBAMD 1
#endif

#ifndef WHALE_HAVE_LIBSMUMPS
#define WHALE_HAVE_LIBSMUMPS 1
#endif

#ifndef WHALE_HAVE_LIBRT
#define WHALE_HAVE_LIBRT 1
#endif

#ifndef WHALE_HAVE_LIBPTSCOTCHERR
#define WHALE_HAVE_LIBPTSCOTCHERR 1
#endif

#ifndef WHALE_HAVE_LIBCMUMPS
#define WHALE_HAVE_LIBCMUMPS 1
#endif

#ifndef WHALE_HAVE_LIBUMFPACK
#define WHALE_HAVE_LIBUMFPACK 1
#endif

#ifndef WHALE_HAVE_LIBPORD
#define WHALE_HAVE_LIBPORD 1
#endif

#ifndef WHALE_HAVE_ERF
#define WHALE_HAVE_ERF 1
#endif

#ifndef WHALE_HAVE_LIBX11
#define WHALE_HAVE_LIBX11 1
#endif

#ifndef WHALE_HAVE_LIBQUADMATH
#define WHALE_HAVE_LIBQUADMATH 1
#endif

#ifndef WHALE_HAVE_TGAMMA
#define WHALE_HAVE_TGAMMA 1
#endif

#ifndef WHALE_HAVE_LIBSCOTCH
#define WHALE_HAVE_LIBSCOTCH 1
#endif

#ifndef WHALE_ARCH
#define WHALE_ARCH "linux-gnu-cxx-opt"
#endif

#ifndef WHALE_DIR
#define WHALE_DIR "/opt/Work/whale"
#endif

#ifndef HAVE_GZIP
#define HAVE_GZIP 1
#endif

#ifndef WHALE_CLANGUAGE_CXX
#define WHALE_CLANGUAGE_CXX 1
#endif

#ifndef WHALE_USE_ERRORCHECKING
#define WHALE_USE_ERRORCHECKING 1
#endif

#ifndef WHALE_MISSING_DREAL
#define WHALE_MISSING_DREAL 1
#endif

#ifndef WHALE_SIZEOF_MPI_COMM
#define WHALE_SIZEOF_MPI_COMM 8
#endif

#ifndef WHALE_BITS_PER_BYTE
#define WHALE_BITS_PER_BYTE 8
#endif

#ifndef WHALE_SIZEOF_MPI_FINT
#define WHALE_SIZEOF_MPI_FINT 4
#endif

#ifndef WHALE_SIZEOF_VOID_P
#define WHALE_SIZEOF_VOID_P 8
#endif

#ifndef WHALE_RETSIGTYPE
#define WHALE_RETSIGTYPE void
#endif

#ifndef WHALE_HAVE_CXX_COMPLEX
#define WHALE_HAVE_CXX_COMPLEX 1
#endif

#ifndef WHALE_SIZEOF_LONG
#define WHALE_SIZEOF_LONG 8
#endif

#ifndef WHALE_USE_FORTRANKIND
#define WHALE_USE_FORTRANKIND 1
#endif

#ifndef WHALE_SIZEOF_SIZE_T
#define WHALE_SIZEOF_SIZE_T 8
#endif

#ifndef WHALE_HAVE_SIGINFO_T
#define WHALE_HAVE_SIGINFO_T 1
#endif

#ifndef WHALE_SIZEOF_CHAR
#define WHALE_SIZEOF_CHAR 1
#endif

#ifndef WHALE_SIZEOF_DOUBLE
#define WHALE_SIZEOF_DOUBLE 8
#endif

#ifndef WHALE_SIZEOF_FLOAT
#define WHALE_SIZEOF_FLOAT 4
#endif

#ifndef WHALE_HAVE_C99_COMPLEX
#define WHALE_HAVE_C99_COMPLEX 1
#endif

#ifndef WHALE_SIZEOF_INT
#define WHALE_SIZEOF_INT 4
#endif

#ifndef WHALE_SIZEOF_LONG_LONG
#define WHALE_SIZEOF_LONG_LONG 8
#endif

#ifndef WHALE_SIZEOF_SHORT
#define WHALE_SIZEOF_SHORT 2
#endif

#ifndef WHALE_HAVE_STRCASECMP
#define WHALE_HAVE_STRCASECMP 1
#endif

#ifndef WHALE_HAVE_GET_NPROCS
#define WHALE_HAVE_GET_NPROCS 1
#endif

#ifndef WHALE_HAVE_POPEN
#define WHALE_HAVE_POPEN 1
#endif

#ifndef WHALE_HAVE_SIGSET
#define WHALE_HAVE_SIGSET 1
#endif

#ifndef WHALE_HAVE_GETWD
#define WHALE_HAVE_GETWD 1
#endif

#ifndef WHALE_HAVE_VSNPRINTF
#define WHALE_HAVE_VSNPRINTF 1
#endif

#ifndef WHALE_HAVE_TIMES
#define WHALE_HAVE_TIMES 1
#endif

#ifndef WHALE_HAVE_DLSYM
#define WHALE_HAVE_DLSYM 1
#endif

#ifndef WHALE_HAVE_SNPRINTF
#define WHALE_HAVE_SNPRINTF 1
#endif

#ifndef WHALE_HAVE_GETPWUID
#define WHALE_HAVE_GETPWUID 1
#endif

#ifndef WHALE_HAVE_GETHOSTBYNAME
#define WHALE_HAVE_GETHOSTBYNAME 1
#endif

#ifndef WHALE_HAVE_GETCWD
#define WHALE_HAVE_GETCWD 1
#endif

#ifndef WHALE_HAVE_DLERROR
#define WHALE_HAVE_DLERROR 1
#endif

#ifndef WHALE_HAVE_FORK
#define WHALE_HAVE_FORK 1
#endif

#ifndef WHALE_HAVE_RAND
#define WHALE_HAVE_RAND 1
#endif

#ifndef WHALE_HAVE_GETTIMEOFDAY
#define WHALE_HAVE_GETTIMEOFDAY 1
#endif

#ifndef WHALE_HAVE_DLCLOSE
#define WHALE_HAVE_DLCLOSE 1
#endif

#ifndef WHALE_HAVE_UNAME
#define WHALE_HAVE_UNAME 1
#endif

#ifndef WHALE_HAVE_GETHOSTNAME
#define WHALE_HAVE_GETHOSTNAME 1
#endif

#ifndef WHALE_HAVE_MKSTEMP
#define WHALE_HAVE_MKSTEMP 1
#endif

#ifndef WHALE_HAVE_SIGACTION
#define WHALE_HAVE_SIGACTION 1
#endif

#ifndef WHALE_HAVE_DRAND48
#define WHALE_HAVE_DRAND48 1
#endif

#ifndef WHALE_HAVE_MEMALIGN
#define WHALE_HAVE_MEMALIGN 1
#endif

#ifndef WHALE_HAVE_VA_COPY
#define WHALE_HAVE_VA_COPY 1
#endif

#ifndef WHALE_HAVE_CLOCK
#define WHALE_HAVE_CLOCK 1
#endif

#ifndef WHALE_HAVE_ACCESS
#define WHALE_HAVE_ACCESS 1
#endif

#ifndef WHALE_HAVE_SIGNAL
#define WHALE_HAVE_SIGNAL 1
#endif

#ifndef WHALE_HAVE_USLEEP
#define WHALE_HAVE_USLEEP 1
#endif

#ifndef WHALE_HAVE_GETRUSAGE
#define WHALE_HAVE_GETRUSAGE 1
#endif

#ifndef WHALE_HAVE_VFPRINTF
#define WHALE_HAVE_VFPRINTF 1
#endif

#ifndef WHALE_HAVE_NANOSLEEP
#define WHALE_HAVE_NANOSLEEP 1
#endif

#ifndef WHALE_HAVE_GETDOMAINNAME
#define WHALE_HAVE_GETDOMAINNAME 1
#endif

#ifndef WHALE_HAVE_TIME
#define WHALE_HAVE_TIME 1
#endif

#ifndef WHALE_HAVE_LSEEK
#define WHALE_HAVE_LSEEK 1
#endif

#ifndef WHALE_HAVE_SOCKET
#define WHALE_HAVE_SOCKET 1
#endif

#ifndef WHALE_HAVE_SYSINFO
#define WHALE_HAVE_SYSINFO 1
#endif

#ifndef WHALE_HAVE_READLINK
#define WHALE_HAVE_READLINK 1
#endif

#ifndef WHALE_HAVE_REALPATH
#define WHALE_HAVE_REALPATH 1
#endif

#ifndef WHALE_HAVE_DLOPEN
#define WHALE_HAVE_DLOPEN 1
#endif

#ifndef WHALE_HAVE_MEMMOVE
#define WHALE_HAVE_MEMMOVE 1
#endif

#ifndef WHALE_HAVE__GFORTRAN_IARGC
#define WHALE_HAVE__GFORTRAN_IARGC 1
#endif

#ifndef WHALE_HAVE_GETPAGESIZE
#define WHALE_HAVE_GETPAGESIZE 1
#endif

#ifndef WHALE_HAVE_SLEEP
#define WHALE_HAVE_SLEEP 1
#endif

#ifndef WHALE_HAVE_VPRINTF
#define WHALE_HAVE_VPRINTF 1
#endif

#ifndef WHALE_HAVE_BZERO
#define WHALE_HAVE_BZERO 1
#endif

#ifndef WHALE_SIGNAL_CAST
#define WHALE_SIGNAL_CAST
#endif

#ifndef WHALE_WRITE_MEMORY_BARRIER
#define WHALE_WRITE_MEMORY_BARRIER() asm volatile("sfence":::"memory")
#endif

#ifndef WHALE_MEMORY_BARRIER
#define WHALE_MEMORY_BARRIER() asm volatile("mfence":::"memory")
#endif

#ifndef WHALE_READ_MEMORY_BARRIER
#define WHALE_READ_MEMORY_BARRIER() asm volatile("lfence":::"memory")
#endif

#ifndef WHALE_CPU_RELAX
#define WHALE_CPU_RELAX() asm volatile("rep; nop" ::: "memory")
#endif

#ifndef WHALE_BLASLAPACK_UNDERSCORE
#define WHALE_BLASLAPACK_UNDERSCORE 1
#endif

#ifndef WHALE_HAVE_MPI_COMM_C2F
#define WHALE_HAVE_MPI_COMM_C2F 1
#endif

#ifndef WHALE_HAVE_MPI_EXSCAN
#define WHALE_HAVE_MPI_EXSCAN 1
#endif

#ifndef WHALE_HAVE_MPI_LONG_DOUBLE
#define WHALE_HAVE_MPI_LONG_DOUBLE 1
#endif

#ifndef WHALE_HAVE_MPI_COMM_F2C
#define WHALE_HAVE_MPI_COMM_F2C 1
#endif

#ifndef WHALE_HAVE_MPI_FINT
#define WHALE_HAVE_MPI_FINT 1
#endif

#ifndef WHALE_HAVE_MPI_F90MODULE
#define WHALE_HAVE_MPI_F90MODULE 1
#endif

#ifndef WHALE_HAVE_MPI_TYPE_GET_ENVELOPE
#define WHALE_HAVE_MPI_TYPE_GET_ENVELOPE 1
#endif

#ifndef WHALE_HAVE_MPI_FINALIZED
#define WHALE_HAVE_MPI_FINALIZED 1
#endif

#ifndef WHALE_HAVE_MPI_COMM_SPAWN
#define WHALE_HAVE_MPI_COMM_SPAWN 1
#endif

#ifndef WHALE_HAVE_MPI_TYPE_GET_EXTENT
#define WHALE_HAVE_MPI_TYPE_GET_EXTENT 1
#endif

#ifndef WHALE_HAVE_MPI_COMBINER_DUP
#define WHALE_HAVE_MPI_COMBINER_DUP 1
#endif

#ifndef WHALE_HAVE_MPI_WIN_CREATE
#define WHALE_HAVE_MPI_WIN_CREATE 1
#endif

#ifndef WHALE_HAVE_MPI_REPLACE
#define WHALE_HAVE_MPI_REPLACE 1
#endif

#ifndef WHALE_HAVE_MPI_TYPE_DUP
#define WHALE_HAVE_MPI_TYPE_DUP 1
#endif

#ifndef WHALE_HAVE_MPIIO
#define WHALE_HAVE_MPIIO 1
#endif

#ifndef WHALE_HAVE_MPI_INIT_THREAD
#define WHALE_HAVE_MPI_INIT_THREAD 1
#endif

#ifndef WHALE_HAVE_MPI_ALLTOALLW
#define WHALE_HAVE_MPI_ALLTOALLW 1
#endif

#ifndef WHALE_HAVE_MPI_IN_PLACE
#define WHALE_HAVE_MPI_IN_PLACE 1
#endif

#ifndef WHALE_USE_SCALAR_REAL
#define WHALE_USE_SCALAR_REAL 1
#endif

#ifndef WHALE_HAVE_ISINF
#define WHALE_HAVE_ISINF 1
#endif

#ifndef WHALE_HAVE_ISNAN
#define WHALE_HAVE_ISNAN 1
#endif

#ifndef WHALE_USE_REAL_DOUBLE
#define WHALE_USE_REAL_DOUBLE 1
#endif

#ifndef WHALE_HAVE_DYNAMIC_LIBRARIES
#define WHALE_HAVE_DYNAMIC_LIBRARIES 1
#endif

#ifndef WHALE_HAVE_SHARED_LIBRARIES
#define WHALE_HAVE_SHARED_LIBRARIES 1
#endif

#ifndef WHALE_USE_SHARED_LIBRARIES
#define WHALE_USE_SHARED_LIBRARIES 1
#endif

#ifndef WHALE_USE_GDB_DEBUGGER
#define WHALE_USE_GDB_DEBUGGER 1
#endif

#ifndef WHALE_USE_PROC_FOR_SIZE
#define WHALE_USE_PROC_FOR_SIZE 1
#endif

#ifndef WHALE_USE_INFO
#define WHALE_USE_INFO 1
#endif

#ifndef WHALE_Alignx
#define WHALE_Alignx(a,b)
#endif

#ifndef WHALE_USE_BACKWARD_LOOP
#define WHALE_USE_BACKWARD_LOOP 1
#endif

#ifndef WHALE_USE_LOG
#define WHALE_USE_LOG 1
#endif

#ifndef WHALE_IS_COLOR_VALUE_TYPE
#define WHALE_IS_COLOR_VALUE_TYPE short
#endif

#ifndef WHALE_USE_CTABLE
#define WHALE_USE_CTABLE 1
#endif

#ifndef WHALE_HAVE_FORTRAN_GET_COMMAND_ARGUMENT
#define WHALE_HAVE_FORTRAN_GET_COMMAND_ARGUMENT 1
#endif

#ifndef WHALE_HAVE_GFORTRAN_IARGC
#define WHALE_HAVE_GFORTRAN_IARGC 1
#endif

#ifndef WHALE_MEMALIGN
#define WHALE_MEMALIGN 16
#endif

#ifndef WHALE_LEVEL1_DCACHE_LINESIZE
#define WHALE_LEVEL1_DCACHE_LINESIZE 64
#endif

#ifndef WHALE_LEVEL1_DCACHE_SIZE
#define WHALE_LEVEL1_DCACHE_SIZE 32768
#endif

#ifndef WHALE_LEVEL1_DCACHE_ASSOC
#define WHALE_LEVEL1_DCACHE_ASSOC 8
#endif

#ifndef WHALE_HAVE_SCHED_CPU_SET_T
#define WHALE_HAVE_SCHED_CPU_SET_T 1
#endif

#ifndef WHALE_HAVE_PTHREAD_BARRIER_T
#define WHALE_HAVE_PTHREAD_BARRIER_T 1
#endif

#ifndef WHALE_HAVE_SYS_SYSCTL_H
#define WHALE_HAVE_SYS_SYSCTL_H 1
#endif

#endif
