#if !defined(__WHALEVERSION_H)
#define __WHALEVERSION_H

#define WHALE_VERSION_RELEASE    1
#define WHALE_VERSION_MAJOR      3
#define WHALE_VERSION_MINOR      4
#define WHALE_VERSION_SUBMINOR   2
#define WHALE_VERSION_PATCH      0
#define WHALE_RELEASE_DATE       "May, 13, 2013"
#define WHALE_VERSION_DATE       "Jul, 02, 2013"

#if !defined (WHALE_VERSION_GIT)
#define WHALE_VERSION_GIT        "a071802d3efee8b987703a6ce2cf5d9a25fa8160"
#endif

#if !defined(WHALE_VERSION_DATE_GIT)
#define WHALE_VERSION_DATE_GIT   "2013-07-02 09:33:06 -0500"
#endif

#define WHALE_VERSION_(MAJOR,MINOR,SUBMINOR) \
  ((WHALE_VERSION_MAJOR == (MAJOR)) &&       \
   (WHALE_VERSION_MINOR == (MINOR)) &&       \
   (WHALE_VERSION_SUBMINOR == (SUBMINOR)) && \
   (WHALE_VERSION_RELEASE  == 1))

#define WHALE_VERSION_LT(MAJOR,MINOR,SUBMINOR)          \
  (WHALE_VERSION_RELEASE == 1 &&                        \
   (WHALE_VERSION_MAJOR < (MAJOR) ||                    \
    (WHALE_VERSION_MAJOR == (MAJOR) &&                  \
     (WHALE_VERSION_MINOR < (MINOR) ||                  \
      (WHALE_VERSION_MINOR == (MINOR) &&                \
       (WHALE_VERSION_SUBMINOR < (SUBMINOR)))))))

#define WHALE_VERSION_LE(MAJOR,MINOR,SUBMINOR) \
  (WHALE_VERSION_LT(MAJOR,MINOR,SUBMINOR) || \
   WHALE_VERSION_(MAJOR,MINOR,SUBMINOR))

#define WHALE_VERSION_GT(MAJOR,MINOR,SUBMINOR) \
  (!WHALE_VERSION_LE(MAJOR,MINOR,SUBMINOR))

#define WHALE_VERSION_GE(MAJOR,MINOR,SUBMINOR) \
  (!WHALE_VERSION_LT(MAJOR,MINOR,SUBMINOR))

#endif
